image: node:16
stages:
  - deploy
  - e2e
  - test

deploy_terraform:
  stage: deploy
  script:
    # Your Review App deployment scripts - for a working example please check https://gitlab.com/Flockademic/Flockademic/blob/5a45f1c2412e93810fab50e2dab8949e2d0633c7/.gitlab-ci.yml#L315
    - echo
    
e2e:chrome:
  stage: e2e
  script: 
    - npm install --prefix nightwatchE2E/
    - npm test --prefix nightwatchE2E/ -- --env ci
  services:
    - selenium/standalone-chrome

test:
    stage: test
    script:
    - yarn install
    - yarn test
