image: node:16
stages:
  - deploy
  - confidence-check
  - test

deploy_terraform:
  stage: deploy
  script:
    # Your Review App deployment scripts - for a working example please check https://gitlab.com/Flockademic/Flockademic/blob/5a45f1c2412e93810fab50e2dab8949e2d0633c7/.gitlab-ci.yml#L315
    - echo
    
e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome:latest

  before_script:
    - npm install

  script:
    - npm install selenium-assistant --save-dev
    - npm install chromedriver --save-dev
    - npm run confidence-check --host=http://selenium:4444/wd/hub

test:
    stage: test
    script:
    - yarn install
    - yarn test
