image: node:16
stages:
  - test
  - confidence-check

test:
    stage: test
    script:
    - yarn install
    - yarn test

e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  script:
    - npm run confidence-check --host=selenium__standalone-chrome