image: node:18

stages:
  - setup
  - build
  - test

variables:
  TEST_BASE_URL: http://localhost:8080
  SELENIUM_HOST: http://localhost:4444/wd/hub

setup:
  stage: setup
  script:
    - apt-get update -qy
    - apt-get install -y wget unzip gnupg2 libu2f-udev libappindicator1 fonts-liberation libgbm1 libgtk-3-0 xdg-utils

    # Install dependencies for Google Chrome
    - apt-get install -y libasound2 libnspr4 libnss3 libvulkan1

    # Install Google Chrome
    - export CHROME_BIN=/usr/bin/google-chrome
    - CHROME_VERSION="115.0.5790.110-1"
    - wget https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
    - dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb || apt-get -f install -y
    - rm google-chrome-stable_${CHROME_VERSION}_amd64.deb

    # Install Chrome Driver
    - CHROME_DRIVER_VERSION=114.0.5735.90
    - wget http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - chmod +x chromedriver
    - mv -f chromedriver /usr/bin/
    - rm chromedriver_linux64.zip

    # Install AdoptOpenJDK 11
    - wget -qO /usr/share/keyrings/adoptopenjdk.asc https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    - echo "deb [signed-by=/usr/share/keyrings/adoptopenjdk.asc] https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ focal main" | tee /etc/apt/sources.list.d/adoptopenjdk.list
    - apt-get update -qy
    - apt-get install -y adoptopenjdk-11-hotspot

    # Run Selenium Standalone server
    - wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-server-4.4.0.jar
    - nohup java -jar selenium-server-4.4.0.jar standalone > selenium.log 2>&1 &

build:
  stage: build
  script:
    - yarn install

test:
  stage: test
  script:
    - export NODE_OPTIONS=--openssl-legacy-provider
    - yarn start &
    - sleep 10 # Wait for the server to start
    - yarn test