image: node:16
stages:
  - test

test:
    stage: test

    services:
    - selenium/standalone-chrome:3.8.1

    variables:
      SELENIUM_URL: "http://selenium__standalone-chrome:4444/wd/hub/"

    before_script:
      - bundle install #Install the required gems
      - export SELENIUM_ENV=remote

    script:
    - yarn install
    - yarn test
