image: node:16
stages:
  - test
  - confidence-check
    
e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  script:
    - npm install selenium-assistant --save-dev
    - npm install chromedriver --save-dev
    - npm run confidence-check --host=selenium__standalone-chrome

test:
    stage: test
    script:
    - yarn install
    - yarn test
