image: node:18

stages:
  - setup
  - test

check:
  stage: setup
  script:
    - apt-get update -qy
    - apt-get install -y wget unzip gnupg2 openjdk-11-jdk
    - wget -qO- https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
    - apt-get update -qy
    - apt-get install -y google-chrome-stable

    - CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
    - wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - mv chromedriver /usr/local/bin/
    - chmod +x /usr/local/bin/chromedriver

    - yarn install
    - yarn global add selenium-standalone
    - selenium-standalone install
  artifacts:
    when: always
    paths:
      - node_modules/

test:
  stage: test
  script:
    - selenium-standalone start &
    - yarn start &
    - sleep 5 # Give Selenium some time to start
    - yarn test
  artifacts:
    when: always
    paths:
      - test-results/
  variables:
    SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub