image: node:18

stages:
  - setup
  - test

check:
  stage: setup
  script:
    # Install/Update Google Chrome browser
    - sudo apt-get install libappindicator1 fonts-liberation libgbm1 libgtk-3-0 xdg-utils
    - export CHROME_BIN=/usr/bin/google-chrome
    - CHROME_VERSION="115.0.5790.110-1"
    - wget https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
    - sudo dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb
    - rm google-chrome-stable_${CHROME_VERSION}_amd64.deb

    # Install/Update Chrome Driver
    - CHROME_DRIVER_VERSION=114.0.5735.90;
    - echo $CHROME_DRIVER_VERSION;
    - wget http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - sudo chmod +x chromedriver
    - sudo mv -f chromedriver /usr/bin/
    - rm chromedriver_linux64.zip

    # Checkout repository
    - actions/checkout@v3

    # Set up Node.js
    - actions/setup-node@v3

    # Install Java
    - sudo apt update
    - sudo apt install -y openjdk-11-jre openjdk-11-jre-headless openjdk-11-jdk openjdk-11-jdk-headless
    
    # Run Selenium Standalone server
    - wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-server-4.4.0.jar
    - nohup java -jar selenium-server-4.4.0.jar standalone > selenium.log 2>&1 & 
         
    # Install dependencies
    - yarn install
  
    # Configure nightwatch.conf.js
    - node webship-init -ci circleci -os linux -b chrome

    # Start virtual server
    - export NODE_OPTIONS=--openssl-legacy-provider
    - yarn start &

    # Run tests
    - yarn test