image: node:16.0
stages:
  - confidence-check

e2e:chrome:
  stage: confidence-check
  services:
    - selenium/standalone-chrome
  before_script:
    - pip3 install -r requirements.txt
  script:
    - yarn install
    - yarn test