image: node:16
stages:
  - test
  - confidence-check

test:
    stage: test

    services:
    - selenium/standalone-chrome

    script:
    - npm install
    - npm run confidence-check --host=selenium__standalone-chrome
    - yarn install
    - yarn test
