#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
        - step:
            name: Selenium linting
            script:
              - npm install selenium
              - npm run http://selenium:4444/wd/hub --host=selenium__standalone-chrome
            caches:
              - node

definitions:
  caches:
     - node
  services:
    hub:
      image: selenium/hub
      environment:
        BROWSER: chrome
    chrome:
      image: selenium/node-chrome:3.141.5
      environment:
        HUB_PORT_4444_TCP_ADDR: 127.0.0.1
        HUB_PORT_4444_TCP_PORT: "4444"