image: node:16

options:
  docker: true

pipelines:
  default:
    - parallel:
      - step:
          name: Run Sample Test Case
          caches:
            - node
          script:
            - yarn install
            - yarn test
  definitions:
  services:
    selenoid:
      image: selenoid/chrome:108.0
            

