#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
    - step:
        name: selenium linting
        script:
          - docker pull selenium/hub:latest
          - docker pull selenium/node-chrome
          - docker run -p 4444:4444 --name selenium-hub selenium/hub
          - docker run --link selenium-hub:hub selenium/node-chrome
          - chmod +x $DRIVERPATH
          - mvn compiler:compile test allure:report
        caches:
          - node
    - step:
        name: Build and Test
        image: node:16
        script:
          - npm install
          - npm test
        caches:
          - node

options:
  docker: true
