image: node:20

pipelines:
  default:
    - step:
        name: Run Sample Test Case
        caches:
          - node
        script:
          - apt-get update
          - apt-get install -y unzip curl
          - yarn install
          - yarn test
        after-script:
          # only needed when testing with tunnel
          - PORT=$(head -1 /tmp/port)
          - status_code=$(curl --request DELETE --write-out %{http_code} --silent --output /dev/null http://127.0.0.1:$PORT/api/v1.0/stop)
          - if [[ "$status_code" -ne 200 ]]; then  pkill LT; fi
          - rm /tmp/port
            
            

