#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
    - parallel:
        - step:
            name: Docker install selenium and chrome
            image: zenika/alpine-chrome
            caches:
              - node
            script:
              - docker version
              - docker pull selenium/hub:latest
              - docker pull selenium/node-chrome
            services:
              - docker
        - step:
            name: 'Run selenium'
            image: nixel2007/docker-selenium-side-runner:latest
            script:
              - selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars,headless]" ./ConsoleTesting.side
              - docker run -p 4444:4444 --name selenium-hub selenium/hub
              - docker run --link selenium-hub:hub selenium/node-chrome
        - step:
            name: npm run test
            max-time: 3
            script:
              - sleep 1m
              - npm install
              - npm test
            caches:
              - node
          

options:
  docker: true
  start_process: true
