image: node:16

options:
  docker: true

pipelines:
  default:
    - parallel:
      - step:
            name: selenium linting
            caches:
              - node
            script:
              - npm install selenium-webdriver
              - java -jar selenium-server-4.4.0.jar standalone
      - step:
          name: Run Sample Test Case
          caches:
            - node
          script:
            - yarn install
            - yarn test
            

