image: node:16

pipelines:
  default:
    - parallel:
      - step:
          name: Run Sample Test Case
          caches:
            - node
          script:
            - yarn install
            - export SELENIUM_HOST=http://selenium:4444/wd/hub
            - yarn test
            
            

