#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  default:
    custom:
   selenium-test:
    - step:
        script:
          - docker version
          - docker build . -t sagargadewar/selenium-test-local
          - docker run -w /usr/src sagargadewar/selenium-test-local mvn clean verify
        services:
          - docker
        caches:
          - docker
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              - npm test
        - step:
            name: Selenium linting
            services:
              - hub
              - chrome
            script:
              - npm install selenium
              - npm run http://selenium:4444/wd/hub --host=selenium__standalone-chrome