image: node:16

pipelines:
  default:
    - step:
        name: Build and Test
        services:
          - selenium/standalone-chrome
        script:
          - yarn install
          - yarn test
            
            

