pipelines:
  custom:
   selenium-test:
    - step:
        script:
          - docker version
          - docker build . -t sagargadewar/selenium-test-local
          - docker run -w /usr/src sagargadewar/selenium-test-local mvn clean verify
        services:
          - docker
        caches:
          - docker