image: node:16
pipelines:
  branches:
    1.0.x:
      - step:
          name: "Webship-js CI"
          caches:
            - node
          script:
            - npm install
            - npm run http://selenium:4444/wd/hub --host=selenium__standalone-chrome
            - npm test
      - parallel:
        - step:
            name: "Selenium Tests"
            caches:
              - node
            services:
              - hub
              - chrome
            script:
              - ./vendor/bin/phpunit --testsuite=selenium --cache-result-file=app/cache/.phpunit.result.cache
