image: atlassian/default-image:3

 

pipelines:

  default:

       - step:

          name: Build and test

          image: zenika/alpine-chrome

          caches:

          - node

          script:

            - docker version

            - docker pull browserless/chrome:latest

          services:

            - docker

         

       - step:

          name: 'Test'

          image: nixel2007/docker-selenium-side-runner:latest

          script:

            - selenium-side-runner -c "browserName=chrome goog:chromeOptions.args=[disable-infobars,headless]" ./ConsoleTesting.side