image: node:16

pipelines:
  default:
    - step:
        name: Webship-js CI
        caches:
          - node
        script:
          - npm install
          - npm run start:test:server
          - npm run http://selenium:4444/wd/hub --host=selenium__standalone-chrome
          - npm test
    