image: node:20

pipelines:
  default:
    - step:
        name: Run Sample Test Case
        caches:
          - node
        script:
          - apt-get update
          - apt-get install -y unzip curl
          - yarn install
          - yarn test
            
            

