version: 2.1
defaults: &defaults
  docker:
    - image: cimg/node:16.18-browsers
      auth:
        username: mydockerhub-user
        password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
commands:
  webship-js-build:
    steps:
      - checkout         
      ## Usefull must have utils.
      - run:
          name: Usefull must have utils
          command: |
            sudo apt -qq update
            sudo apt -qqy upgrade
            sudo apt -yqq install p7zip-full unzip zip libfreetype6-dev libaio1 libaio-dev libonig-dev libpng-dev
            sudo apt -yqq install xvfb libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 libnss3

      ## Configure and run the virtual display.
      - run:
          name: Configure and run the virtual display.
          command: Xvfb -ac :99 -screen 0 1600x1200x24 > /dev/null 2>&1
          background: true

      ## Install/Update Google Chrome browser.
      - run:
          name: Install/Update Google Chrome browser
          command: |
            sudo apt-get install libappindicator1 fonts-liberation libgbm1 libgtk-3-0 xdg-utils
            export CHROME_BIN=/usr/bin/google-chrome
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb
            rm google-chrome-stable_current_amd64.deb

      ## Install/Update Chrome Driver.
      - run:
          name: Install/Update Chrome Driver
          command: |
            CHROME_DRIVER_VERSION=$(wget -qO- chromedriver.storage.googleapis.com/LATEST_RELEASE);
            echo $CHROME_DRIVER_VERSION;
            wget http://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo chmod +x chromedriver
            sudo mv -f chromedriver /usr/bin/
            rm chromedriver_linux64.zip
      
       ## Setup Apache2
      - run:
          name: Setup Apache2
          command: |
            sudo apt install -yqq apache2

      ## Run Selenium Standalone server.
      - run:
          name: Run Selenium Standalone server
          command: |
            java -jar selenium-server-standalone-3.141.59.jar -port 4444
          background: true
  
jobs:
  webship-js-testing:
    <<: *defaults
    steps:
      - webship-js-build
      ## Automated Functional Acceptance Testing
      - run:
          name: Automated Functional Acceptance Testing
          no_output_timeout: 30m
          command: |
            yarn install
            yarn test

workflows:
  version: 2
  webship-js-workflow:
    jobs:
      - webship-js-testing:
          filters:
            tags:
              only: /^1.0.*/
            branches:
              only: /^1.0.x/

