name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080
      SELENIUM_HOST: http://selenium:4444/wd/hub

    steps:
      - name: Install Chrome
        run: |
         sudo apt install libu2f-udev
            sudo apt-get install libappindicator1 fonts-liberation libgbm1 libgtk-3-0 xdg-utils
            export CHROME_BIN=/usr/bin/google-chrome
            CHROME_VERSION="120.0.6099.109-1"
            wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_VERSION/linux64/chrome-linux64.zip
            unzip chrome-linux64.zip
            sudo chmod +x chrome
            sudo mv -f chrome /usr/bin/
            rm chrome-linux64.zip
      - name: Install/Update Chrome Driver
        run: |
          CHROME_DRIVER_VERSION=120.0.6099.109;
          echo $CHROME_DRIVER_VERSION;
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/$CHROME_DRIVER_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo chmod +x chromedriver
          sudo mv -f chromedriver /usr/bin/
          rm chromedriver-linux64.zip

      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: install selenium
        run: wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.16.1/selenium-server-4.16.1.jar
      - name: run selenium
        run: java -jar selenium-server-4.16.1.jar standalone > /dev/null 2>&1 &

      - name: Install
        run: yarn install
      - name: Configure nightwatch.conf.js for Github
        run: node webship-init -ci github -os linux -b chrome
      - name: Test
        run: yarn test