name: Github Actions
on:
  push:
    branches:
      - 'main'
      - 'next'
  pull_request:

jobs:
  test:
    name: 'node ${{ matrix.node }} chrome ${{ matrix.os }} '
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - uses: actions/checkout@v2
      - name: npm install and validate
        run: |
          export CHROMEDRIVER_VERSION="$(chromedriver --version | awk '{print $2}')"
          npm install
          npm run validate
        env:
          CI: true

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn test
      