name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8000
      SELENIUM_HOST: http://selenium:4444/wd/hub

    steps:
      - uses: actions/checkout@v2
      - run: echo "Running the tests"
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - uses: nanasess/setup-chromedriver@v1.0.7
      - run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &

      - name: install selenium
        run: wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.1.0/selenium-server-4.1.2.jar
      - name: run selenium
        run: java -jar selenium-server-4.1.2.jar standalone > /dev/null 2>&1 &

           
      - name: Install
        run: yarn install
      - name: Configure nightwatch.conf.js for Github
        run: node webship-init -ci github -os linux -b chrome
      - name: Test
        run: yarn test