name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080
      SELENIUM_HOST: http://localhost:4444/wd/hub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          MAJOR_CHROME_VERSION=$(echo $CHROME_VERSION | cut -d '.' -f 1)
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${MAJOR_CHROME_VERSION})
          if [ -z "$CHROMEDRIVER_VERSION" ]; then
            echo "Failed to obtain ChromeDriver version for Chrome version $CHROME_VERSION"
            exit 1
          fi
          wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv -f chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      - name: Run Selenium Standalone Server
        run: |
          wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-server-4.4.0.jar
          nohup java -jar selenium-server-4.4.0.jar standalone > selenium.log 2>&1 &
          sleep 5
          cat selenium.log

      - name: Wait for Selenium Standalone Server to be ready
        run: |
          timeout 30s bash -c 'until echo > /dev/tcp/localhost/4444; do sleep 1; done'

      - name: Install dependencies
        run: yarn install

      - name: Configure nightwatch.conf.js for GitHub
        run: node webship-init -ci github -os linux -b chrome

      - name: Start virtual server
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn start &

      - name: Run tests
        run: yarn test