name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080/
      SELENIUM_HOST: http://selenium:4444/wd/hub

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
      - name: Install Chrome
        run: |
          CHROME_VERSION="116.0.5845.96-1"
          wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
          sudo dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb
      - name: Install
        run: yarn install
      - name: Configure nightwatch.conf.js for Github
        run: node webship-init -ci github -os linux -b chrome
      - name: Start
        run: yarn start &
      - name: Test
        run: yarn test