name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080/
      SELENIUM_HOST: http://selenium:4444/wd/hub

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Replace config file
        run: npm rm -f /nightwatch.conf.js
        run: cp /assets/config_templates/nightwatch-github-chrome.conf.js /nightwatch.conf.js
      - name: Install
        run: yarn install
      - name: Start
        run: yarn start &
      - name: Test
        run: yarn test