name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080

    steps:
      - uses: actions/checkout@v3

    # Install specific version of Chrome
      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'stable'
        
      - name: Install ChromeDriver
        uses: browser-actions/setup-chromedriver@v2

      - name: Check versions
        run: |
          google-chrome --version
          chromedriver --version
      
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Run Selenium Standalone server
        run: |
            wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.1.0/selenium-server-4.1.2.jar
            java -jar selenium-server-4.1.2.jar -role node -hub http://localhost:4444

      - name: Install
        run: yarn install
      - name: Configure nightwatch.conf.js for Github
        run: node webship-init -ci github -os linux -b chrome
      - name: Test
        run: yarn test