name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080
      SELENIUM_HOST: http://localhost:4444/wd/hub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          CHROME_VERSION="115.0.5790.110-1"
          wget https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
          sudo dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb
          sudo apt-get install -f

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv -f chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Selenium Standalone server
        run: |
          wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-server-4.4.0.jar
          nohup java -jar selenium-server-4.4.0.jar standalone > selenium.log 2>&1 &

      - name: Wait for Selenium Standalone server to be ready
        run: |
          timeout 15s bash -c 'until echo > /dev/tcp/localhost/4444; do sleep 1; done'

      - name: Install dependencies
        run: yarn install

      - name: Configure nightwatch.conf.js for GitHub
        run: node webship-init -ci github -os linux -b chrome

      - name: Start virtual server
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn start &

      - name: Run tests
        run: yarn test