name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080/
      SELENIUM_HOST: http://selenium:4444/wd/hub

    services:
      selenium:
        image: selenium/standalone-chrome
        # options: --health-cmd "curl http://selenium:4444" --health-interval=5s
        ports: 
          - 4444:4444

      webpack:
        image: webpack/webpack-dev-server
          - run: npm install webpack-dev-server --save-dev
          - run: webpack serve --open --port 8080
        ports: 
          - 8080:8080

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: yarn install
      - run: yarn test