name: Github Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080
      SELENIUM_HOST: http://localhost:4444/wd/hub

    steps:
      - name: Install/Update Google Chrome browser
        run: |
          sudo apt install -y libu2f-udev
          sudo apt-get install -y libgbm1 libvulkan1 libnss3 libgconf-2-4 libxss1 fonts-liberation libappindicator3-1 libatk-bridge2.0-0 xdg-utils libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libnss3 libxss1 libasound2 libxtst6 xauth
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f
          rm google-chrome-stable_current_amd64.deb
          sudo chmod +x /usr/bin/google-chrome
          /usr/bin/google-chrome --version
          google-chrome --version

      - name: Install/Update Chrome Driver
        run: |
          CHROME_VERSION=$(google-chrome --product-version)
          echo $CHROME_VERSION
          wget https://storage.googleapis.com/chrome-for-testing-public/$CHROME_VERSION/linux64/chromedriver-linux64.zip
          unzip chromedriver-linux64.zip
          sudo chmod +x chromedriver-linux64/chromedriver
          sudo mv -f chromedriver-linux64/chromedriver /usr/bin/
          rm -rf chromedriver-linux64.zip chromedriver-linux64
          chromedriver --version

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Run Selenium Standalone server
        run: |
          wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-server-4.4.0.jar
          nohup java -jar selenium-server-4.4.0.jar standalone > selenium.log 2>&1 &

      - name: Install dependencies
        run: yarn install

      - name: Configure nightwatch.conf.js for GitHub
        run: node webship-init -ci github -os linux -b chrome

      - name: Start virtual server
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          yarn start &

      - name: Run tests
        run: yarn test