name: Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TEST_BASE_URL: http://localhost:8080
      SELENIUM_HOST: http://selenium:4444/wd/hub

    steps:
      - name: Install Chrome
        run: |
          CHROME_VERSION="115.0.5790.110-1"
          wget https://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
          sudo dpkg -i google-chrome-stable_${CHROME_VERSION}_amd64.deb
            
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Run Selenium Standalone server
        run: |
          wget https://github.com/SeleniumHQ/selenium/releases/download/selenium-4.4.0/selenium-server-4.4.0.jar
          java -jar selenium-server-4.4.0.jar standalone
      
      - name: Install
        run: yarn install
      - name: Configure nightwatch.conf.js for Github
        run: node webship-init -ci github -os linux -b chrome
      - name: Start virtual server
        run: |
            export NODE_OPTIONS=--openssl-legacy-provider
            yarn start &
      - name: Test
        run: yarn test